### ISSUE TITLE
Conflict with bootstrap css

### ISSUE THREAD

**Issue by changbaishan** [MrMufflon/Leaflet.Coordinates#20]
There is a possible conflict with bootstrap css. If you add bootstrap css(<link
	href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"
	rel="stylesheet">), Latlng will not be displayed.

**Comment by MrMufflon** [comment]
Fixed in a4042c165700f4ba568e5aab4bd792e3babed835
